site_name: Z4K
theme:
  name: readthedocs
  highlightjs: false
nav:
- Home: index.md
- Prerequisites and Requirements: MinimumRequirements.md
- Z4K Deployment Architecture: DeployingZertoForK8S.md
- Deployment Guide: HowToDeployZerto.md
- Administration Guide: HowToRunZertoOperations.md
- Supported Platforms: SupportedPlatforms.md
- More Resources: MoreResources.md
- API Documentation: openapi.md
- ChangeLog:
  - No Changes
plugins:
- zerto_swagger
