site_name: Z4K

theme:
    name: readthedocs
    highlightjs: true

nav:
  - Home: index.md
  - Requirements: MinimumRequirements.md
  - Z4K Deployment Architecture: DeployingZertoForK8S.md
  - How To Deploy Zerto: HowToDeployZerto.md
  - How To Run Zerto Operations: HowToRunZertoOperations.md
  - Supported Platforms: SupportedPlatforms.md
  - More Resources: MoreResources.md
  - Quick Reference: openapi.md
  - Changes:
    - '1.0': ./changes/version1.x.x.md
    - 2.0: ./changes/version2.x.x.md

plugins:
  - render_swagger
  
