site_name: Zerto for Kubernetes (Z4K)
theme:
  name: readthedocs
  highlightjs: false
nav:
- Zerto for Kubernetes Overview: Z4KOverview.md
- Zerto for Kubernetes Overview:
  - Deployment Architecture: DeploymentArchitecture.md
  - Supported Platforms: SupportedPlatforms.md
  - Limitations: Limitations.md
  - Known Issues: Known_Issues.md
  - Release Updates: ReleaseNotes.md
- Z4K Deployment: Z4KDeployment.md
- Z4K Deployment:
  - Prerequisites and Requirements: PrerequisitesAndRequirements.md
  - Deploying Z4K: Z4KDeploymentGuide.md
  - Taints and Tolerations: TaintsandTolerations.md
  - Upgrading Z4K: UpgradingZ4K.md
  - Uninstalling Z4K: UninstallingZ4K.md
- Z4K Administration: Z4KAdministrationGuide.md
- Z4K REST API: Z4KRESTAPI.md
- Z4K REST API:
  - Accessing the Z4K REST API: AccessingZ4KRESTAPI.md
  - Z4K APIs: openapi.md
- Z4K Analytics: Z4KAnalytics.md
- Troubleshooting
  - Collecting Z4K Logs: LogCollection.md
plugins:
- zerto_swagger
- search
markdown_extensions:
  - tables
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
