site_name: Z4K
theme:
  name: readthedocs
  highlightjs: false
nav:
- Home: index.md
- Prerequisites and Requirements: MinimumRequirements.md
- Z4K Deployment Architecture: DeployingZertoForK8S.md
- Deployment Guide: DeploymentGuide.md
- Administration Guide: AdministrationGuide.md
- Supported Platforms: SupportedPlatforms.md
- More Resources: MoreResources.md
- API Documentation: openapi.md
- ChangeLog:
  - '2.x.x': ./changes/version2.x.x.md
plugins:
- zerto_swagger
- search
