site_name: Z4K
theme:
  name: readthedocs
  highlightjs: false
nav:
- Zerto for Kubernetes Overview: index.md
- Prerequisites and Requirements: MinimumRequirements.md
- Supported Platforms: SupportedPlatforms.md
- Deployment: DeploymentGuide.md
- Administration: AdministrationGuide.md
- Z4K Analytics: Z4KAnalytics.md
- Accessing the Z4K Open API: AccessingOpenAPI.md
- API Documentation: openapi.md
- More Resources: MoreResources.md
- ChangeLog:
  - '2.x.x': ./changes/version2.x.x.md
plugins:
- zerto_swagger
- search
markdown_extensions:
  - tables
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
