site_name: Zerto for Kubernetes (Z4K)
theme:
  name: zoomindocs
  highlightjs: false
nav:
- Zerto for Kubernetes Overview: Z4KOverview.md
- Zerto for Kubernetes Overview: 
  - Deployment Architecture: DeploymentArchitecture.md
  - Supported Platforms: SupportedPlatforms.md
  - Release Updates: ReleaseNotes.md
  - Limitations: Limitations.md
  - Known Issues: Known_Issues.md
- Z4K Deployment: Z4KDeployment.md
- Z4K Deployment:
  - Prerequisites and Requirements: PrerequisitesAndRequirements.md
  - Deploying Z4K: Z4KDeploymentGuide.md
  - Taints and Tolerations: TaintsandTolerations.md
  - Upgrading Z4K: UpgradingZ4K.md
  - Uninstalling Z4K: UninstallingZ4K.md
- Z4K Administration: Z4kAdministration.md
- Z4K Administration:
  - Configuring Virtual Protection Groups: ConfiguringVPGs.md
  - Backing up to the Extended Journal Copy: ExtendedJournalCopy.md
  - Disaster Recovery: DisasterRecovery.md
- Z4K REST API:
  - Accessing the Z4K REST API: AccessingZ4KRESTAPI.md
  - Z4K APIs: openapi.md
- Z4K Analytics:
- Troubleshooting Z4K: TroubleshootingZ4K.md
- Troubleshooting Z4K:
  - Collecting Z4K Logs: LogCollection.md
plugins:
- zerto_swagger
- search
markdown_extensions:
  - tables
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
