site_name: Z4K
theme:
  name: readthedocs
  highlightjs: false
nav:
- Zerto for Kubernetes Overview: Z4KOverview.md
- Deployment Architecture: DeploymentArchitecture.md
- Prerequisites and Requirements: PrerequisitesAndRequirements.md
- Supported Platforms: SupportedPlatforms.md
- Z4K Deployment: Z4KDeploymentGuide.md
- Z4K Administration: Z4KAdministrationGuide.md
- Z4K Analytics: Z4KAnalytics.md
- Accessing the Z4K REST API: AccessingZ4KRESTAPI.md
- Z4K REST API: openapi.md
- More Resources: MoreResources.md
- Change Log: ./changes/ChangeLog.md
 plugins:
- zerto_swagger
- search
markdown_extensions:
  - tables
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
