site_name: Z4K
theme:
  name: readthedocs
  highlightjs: false
nav:
- Zerto for Kubernetes Overview: index.md
- Prerequisites and Requirements: MinimumRequirements.md
- Z4K Deployment Architecture: DeployingZertoForK8S.md
- Deployment Guide: HowToDeployZerto.md
- Administration Guide: HowToRunZertoOperations.md
- Supported Platforms: SupportedPlatforms.md
- Z4K Analytics: Z4KAnalytics.md
- More Resources: MoreResources.md
- API Documentation: openapi.md
- ChangeLog:
  - '2.x.x': ./changes/version2.x.x.md
plugins:
- zerto_swagger
- search
markdown_extensions:
  - tables
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
