site_name: Z4K

theme:
    name: readthedocs
    highlightjs: true

nav:
  - Home: index.md
  - Requirements: MinimumRequirements.md
  - Deploy: DeployingZertoForK8S.md
  - HOW TO: HowToDeployZerto.md
  - Run Zerto Operations: HowToRunZertoOperations.md
  - Supported Platforms: SupportedPlatforms.md
  - More Resources: MoreResources.md
  