site_name: Zerto for Kubernetes (Z4K)
theme:
  name: readthedocs
  highlightjs: false
nav:
- Zerto for Kubernetes Overview: Z4KOverview.md
- Zerto for Kubernetes Overview:
  - Deployment Architecture: DeploymentArchitecture.md
  - Limitations: Limitations.md
  - Known Issues: Known_Issues.md
- Z4K Deployment:
  - Prerequisites and Requirements: PrerequisitesAndRequirements.md
  - Supported Platforms: SupportedPlatforms.md
  - Deploying Z4K: Z4KDeploymentGuide.md
  - Z4K Taints and Tolerations: TaintsandTolerations.md
- Z4K Administration: Z4KAdministrationGuide.md
- Z4K Log Collection: LogCollection.md
- Z4K Analytics: Z4KAnalytics.md
- Z4K REST API:
- Z4K REST API:
  - Z4K REST API: Z4KRESTAPI.md
  - Accessing the Z4K REST API: AccessingZ4KRESTAPI.md
  - Z4K APIs: openapi.md
- More Resources: MoreResources.md
- ChangeLog:
  - '2.x.x': ./changes/version2.x.x.md
plugins:
- zerto_swagger
- search
markdown_extensions:
  - tables
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
